### ISSUE TITLE
It crashes the server

### ISSUE THREAD

**Issue by ZehuaMc** [haKingdomsCraft/SimpleShopGUI#1]
Altay Crash Dump Thu Jul 19 23:13:17 UTC 2018

Error: Declaration of GuiShop\Modals\network\GuiDataPickItemPacket::decodePayload() must be compatible with pocketmine\network\mcpe\protocol\DataPacket::decodePayload(): void
File: SimpleShopGUI-master/src/GuiShop/Modals/network/GuiDataPickItemPacket
Line: 27
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SimpleShopGUI v1.0.0-BETA2

Code:

Backtrace:

Altay version: 3.0.7 [Protocol 274]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 4.4.78-perf-gea7f933 #1 SMP PREEMPT Fri Jun 22 01:23:48 CST 2018 aarch64
PHP Version: 7.2.3
Zend version: 3.2.0
OS : Linux, android

Loaded plugins:
PiggyCustomEnchants 1.2.0 by DaPigGuy for API(s) 3.0.0
PiggyCustomEnchantsShop 1.1.0 by DaPigGuy for API(s) 3.0.0
Shipyard 1.0.0-ALPHA by AndreasHGK for API(s) 3.0.0
SimpleShopGUI 1.0.0-BETA2 by TrexCraft Devz for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0, 4.0.0+dev.1224, 4.0.0, 3.0.0-ALPHA12
McWorld 1.0.1 by Mcdowell for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.1, 4.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
MyStats 1.4.13 by CzechMPDevs, VixikCZ for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
VanillaEnchantments 3.1.0_ALPHA by TheAz928 for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12
EconomySell 2.0.8 by onebone for API(s) 3.0.0
EconomyShop 2.0.9 by onebone for API(s) 3.0.0

**Comment by haKingdomsCraft** [comment]
Your Ver?
